spring:
  application:
    name: passkeys-sample
  main:
    banner-mode: off
  profiles:
    active: dev

logging:
  level:
    root: info
    org.springframework: warn
    org.apache.catalina: warn
    org.apache.tomcat: warn
